### ISSUE TITLE
better-dom 4 roadmap

### ISSUE THREAD

**Issue by chemerisuk** [chemerisuk/better-dom#43]
- [ ] decrease number of internal objects created
- [ ] drop `$Element#data`/`$Element#toggle`
- [ ] functor as a returned value for `$Element#on`, drop `$Element#on`
- [ ] drop support for IE8-9
- [ ] drop support for legacy Opera
- [ ] drop support for legacy Android browser
- [ ] store API documentation on Wiki
